/* This file was generated by upbc (the upb compiler) from the input
 * file:
 *
 *     s2a/src/proto/s2a.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated. */

#include <stddef.h>
#include "upb/msg_internal.h"
#include "s2a/src/proto/upb-generated/s2a/src/proto/s2a.upb.h"
#include "s2a/src/proto/upb-generated/s2a/src/proto/common.upb.h"

#include "upb/port_def.inc"

static const upb_msglayout *const s2a_proto_AuthenticationMechanism_submsgs[1] = {
  &s2a_proto_Identity_msginit,
};

static const upb_msglayout_field s2a_proto_AuthenticationMechanism__fields[2] = {
  {1, UPB_SIZE(4, 8), 1, 0, 11, _UPB_MODE_SCALAR},
  {2, UPB_SIZE(8, 16), UPB_SIZE(-17, -33), 0, 9, _UPB_MODE_SCALAR},
};

const upb_msglayout s2a_proto_AuthenticationMechanism_msginit = {
  &s2a_proto_AuthenticationMechanism_submsgs[0],
  &s2a_proto_AuthenticationMechanism__fields[0],
  UPB_SIZE(24, 48), 2, false, 2, 255,
};

static const upb_msglayout *const s2a_proto_ClientSessionStartReq_submsgs[1] = {
  &s2a_proto_Identity_msginit,
};

static const upb_msglayout_field s2a_proto_ClientSessionStartReq__fields[7] = {
  {1, UPB_SIZE(24, 40), 0, 0, 9, _UPB_MODE_ARRAY},
  {2, UPB_SIZE(4, 4), 0, 0, 14, _UPB_MODE_SCALAR},
  {3, UPB_SIZE(8, 8), 0, 0, 14, _UPB_MODE_SCALAR},
  {4, UPB_SIZE(28, 48), 0, 0, 14, _UPB_MODE_ARRAY | _UPB_MODE_IS_PACKED},
  {5, UPB_SIZE(32, 56), 0, 0, 11, _UPB_MODE_ARRAY},
  {6, UPB_SIZE(20, 32), 1, 0, 11, _UPB_MODE_SCALAR},
  {7, UPB_SIZE(12, 16), 0, 0, 9, _UPB_MODE_SCALAR},
};

const upb_msglayout s2a_proto_ClientSessionStartReq_msginit = {
  &s2a_proto_ClientSessionStartReq_submsgs[0],
  &s2a_proto_ClientSessionStartReq__fields[0],
  UPB_SIZE(40, 64), 7, false, 7, 255,
};

static const upb_msglayout *const s2a_proto_ServerSessionStartReq_submsgs[1] = {
  &s2a_proto_Identity_msginit,
};

static const upb_msglayout_field s2a_proto_ServerSessionStartReq__fields[6] = {
  {1, UPB_SIZE(16, 24), 0, 0, 9, _UPB_MODE_ARRAY},
  {2, UPB_SIZE(0, 0), 0, 0, 14, _UPB_MODE_SCALAR},
  {3, UPB_SIZE(4, 4), 0, 0, 14, _UPB_MODE_SCALAR},
  {4, UPB_SIZE(20, 32), 0, 0, 14, _UPB_MODE_ARRAY | _UPB_MODE_IS_PACKED},
  {5, UPB_SIZE(24, 40), 0, 0, 11, _UPB_MODE_ARRAY},
  {6, UPB_SIZE(8, 8), 0, 0, 12, _UPB_MODE_SCALAR},
};

const upb_msglayout s2a_proto_ServerSessionStartReq_msginit = {
  &s2a_proto_ServerSessionStartReq_submsgs[0],
  &s2a_proto_ServerSessionStartReq__fields[0],
  UPB_SIZE(32, 48), 6, false, 6, 255,
};

static const upb_msglayout_field s2a_proto_SessionNextReq__fields[1] = {
  {1, UPB_SIZE(0, 0), 0, 0, 12, _UPB_MODE_SCALAR},
};

const upb_msglayout s2a_proto_SessionNextReq_msginit = {
  NULL,
  &s2a_proto_SessionNextReq__fields[0],
  UPB_SIZE(8, 16), 1, false, 1, 255,
};

static const upb_msglayout *const s2a_proto_ResumptionTicketReq_submsgs[1] = {
  &s2a_proto_Identity_msginit,
};

static const upb_msglayout_field s2a_proto_ResumptionTicketReq__fields[3] = {
  {1, UPB_SIZE(20, 24), 0, 0, 12, _UPB_MODE_ARRAY},
  {2, UPB_SIZE(8, 8), 0, 0, 4, _UPB_MODE_SCALAR},
  {3, UPB_SIZE(16, 16), 1, 0, 11, _UPB_MODE_SCALAR},
};

const upb_msglayout s2a_proto_ResumptionTicketReq_msginit = {
  &s2a_proto_ResumptionTicketReq_submsgs[0],
  &s2a_proto_ResumptionTicketReq__fields[0],
  UPB_SIZE(24, 32), 3, false, 3, 255,
};

static const upb_msglayout *const s2a_proto_SessionReq_submsgs[5] = {
  &s2a_proto_AuthenticationMechanism_msginit,
  &s2a_proto_ClientSessionStartReq_msginit,
  &s2a_proto_ResumptionTicketReq_msginit,
  &s2a_proto_ServerSessionStartReq_msginit,
  &s2a_proto_SessionNextReq_msginit,
};

static const upb_msglayout_field s2a_proto_SessionReq__fields[5] = {
  {1, UPB_SIZE(4, 8), UPB_SIZE(-9, -17), 1, 11, _UPB_MODE_SCALAR},
  {2, UPB_SIZE(4, 8), UPB_SIZE(-9, -17), 3, 11, _UPB_MODE_SCALAR},
  {3, UPB_SIZE(4, 8), UPB_SIZE(-9, -17), 4, 11, _UPB_MODE_SCALAR},
  {4, UPB_SIZE(4, 8), UPB_SIZE(-9, -17), 2, 11, _UPB_MODE_SCALAR},
  {5, UPB_SIZE(0, 0), 0, 0, 11, _UPB_MODE_ARRAY},
};

const upb_msglayout s2a_proto_SessionReq_msginit = {
  &s2a_proto_SessionReq_submsgs[0],
  &s2a_proto_SessionReq__fields[0],
  UPB_SIZE(16, 24), 5, false, 5, 255,
};

static const upb_msglayout_field s2a_proto_SessionState__fields[10] = {
  {1, UPB_SIZE(0, 0), 0, 0, 14, _UPB_MODE_SCALAR},
  {2, UPB_SIZE(4, 4), 0, 0, 14, _UPB_MODE_SCALAR},
  {3, UPB_SIZE(8, 8), 0, 0, 4, _UPB_MODE_SCALAR},
  {4, UPB_SIZE(16, 16), 0, 0, 4, _UPB_MODE_SCALAR},
  {5, UPB_SIZE(36, 40), 0, 0, 12, _UPB_MODE_SCALAR},
  {6, UPB_SIZE(44, 56), 0, 0, 12, _UPB_MODE_SCALAR},
  {7, UPB_SIZE(52, 72), 0, 0, 12, _UPB_MODE_SCALAR},
  {8, UPB_SIZE(60, 88), 0, 0, 12, _UPB_MODE_SCALAR},
  {9, UPB_SIZE(24, 24), 0, 0, 4, _UPB_MODE_SCALAR},
  {10, UPB_SIZE(32, 32), 0, 0, 8, _UPB_MODE_SCALAR},
};

const upb_msglayout s2a_proto_SessionState_msginit = {
  NULL,
  &s2a_proto_SessionState__fields[0],
  UPB_SIZE(72, 112), 10, false, 10, 255,
};

static const upb_msglayout *const s2a_proto_SessionResult_submsgs[2] = {
  &s2a_proto_Identity_msginit,
  &s2a_proto_SessionState_msginit,
};

static const upb_msglayout_field s2a_proto_SessionResult__fields[6] = {
  {1, UPB_SIZE(4, 8), 0, 0, 9, _UPB_MODE_SCALAR},
  {2, UPB_SIZE(28, 56), 1, 1, 11, _UPB_MODE_SCALAR},
  {4, UPB_SIZE(32, 64), 2, 0, 11, _UPB_MODE_SCALAR},
  {5, UPB_SIZE(36, 72), 3, 0, 11, _UPB_MODE_SCALAR},
  {6, UPB_SIZE(12, 24), 0, 0, 12, _UPB_MODE_SCALAR},
  {7, UPB_SIZE(20, 40), 0, 0, 12, _UPB_MODE_SCALAR},
};

const upb_msglayout s2a_proto_SessionResult_msginit = {
  &s2a_proto_SessionResult_submsgs[0],
  &s2a_proto_SessionResult__fields[0],
  UPB_SIZE(40, 80), 6, false, 2, 255,
};

static const upb_msglayout_field s2a_proto_SessionStatus__fields[2] = {
  {1, UPB_SIZE(0, 0), 0, 0, 13, _UPB_MODE_SCALAR},
  {2, UPB_SIZE(4, 8), 0, 0, 9, _UPB_MODE_SCALAR},
};

const upb_msglayout s2a_proto_SessionStatus_msginit = {
  NULL,
  &s2a_proto_SessionStatus__fields[0],
  UPB_SIZE(16, 32), 2, false, 2, 255,
};

static const upb_msglayout *const s2a_proto_SessionResp_submsgs[3] = {
  &s2a_proto_Identity_msginit,
  &s2a_proto_SessionResult_msginit,
  &s2a_proto_SessionStatus_msginit,
};

static const upb_msglayout_field s2a_proto_SessionResp__fields[5] = {
  {1, UPB_SIZE(16, 24), 1, 0, 11, _UPB_MODE_SCALAR},
  {2, UPB_SIZE(8, 8), 0, 0, 12, _UPB_MODE_SCALAR},
  {3, UPB_SIZE(4, 4), 0, 0, 13, _UPB_MODE_SCALAR},
  {4, UPB_SIZE(20, 32), 2, 1, 11, _UPB_MODE_SCALAR},
  {5, UPB_SIZE(24, 40), 3, 2, 11, _UPB_MODE_SCALAR},
};

const upb_msglayout s2a_proto_SessionResp_msginit = {
  &s2a_proto_SessionResp_submsgs[0],
  &s2a_proto_SessionResp__fields[0],
  UPB_SIZE(32, 48), 5, false, 5, 255,
};

#include "upb/port_undef.inc"

