/* This file was generated by upbc (the upb compiler) from the input
 * file:
 *
 *     s2a/src/proto/s2a_context.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated. */

#include <stddef.h>
#include "upb/msg_internal.h"
#include "s2a/src/proto/upb-generated/s2a/src/proto/s2a_context.upb.h"
#include "s2a/src/proto/upb-generated/s2a/src/proto/common.upb.h"

#include "upb/port_def.inc"

static const upb_msglayout *const s2a_proto_S2AContext_submsgs[1] = {
  &s2a_proto_Identity_msginit,
};

static const upb_msglayout_field s2a_proto_S2AContext__fields[8] = {
  {1, UPB_SIZE(16, 16), 0, 0, 9, _UPB_MODE_SCALAR},
  {2, UPB_SIZE(4, 4), 0, 0, 14, _UPB_MODE_SCALAR},
  {3, UPB_SIZE(8, 8), 0, 0, 14, _UPB_MODE_SCALAR},
  {4, UPB_SIZE(40, 64), 1, 0, 11, _UPB_MODE_SCALAR},
  {5, UPB_SIZE(44, 72), 2, 0, 11, _UPB_MODE_SCALAR},
  {6, UPB_SIZE(24, 32), 0, 0, 12, _UPB_MODE_SCALAR},
  {7, UPB_SIZE(32, 48), 0, 0, 12, _UPB_MODE_SCALAR},
  {8, UPB_SIZE(12, 12), 0, 0, 8, _UPB_MODE_SCALAR},
};

const upb_msglayout s2a_proto_S2AContext_msginit = {
  &s2a_proto_S2AContext_submsgs[0],
  &s2a_proto_S2AContext__fields[0],
  UPB_SIZE(48, 80), 8, false, 8, 255,
};

#include "upb/port_undef.inc"

