/* This file was generated by upbc (the upb compiler) from the input
 * file:
 *
 *     proto/s2a.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated. */

#ifndef PROTO_S2A_PROTO_UPB_H_
#define PROTO_S2A_PROTO_UPB_H_

#include "upb/msg.h"
#include "upb/decode.h"
#include "upb/decode_fast.h"
#include "upb/encode.h"

#include "upb/port_def.inc"

#ifdef __cplusplus
extern "C" {
#endif

struct s2a_proto_AuthenticationMechanism;
struct s2a_proto_ClientSessionStartReq;
struct s2a_proto_ServerSessionStartReq;
struct s2a_proto_SessionNextReq;
struct s2a_proto_ResumptionTicketReq;
struct s2a_proto_SessionReq;
struct s2a_proto_SessionState;
struct s2a_proto_SessionResult;
struct s2a_proto_SessionStatus;
struct s2a_proto_SessionResp;
typedef struct s2a_proto_AuthenticationMechanism s2a_proto_AuthenticationMechanism;
typedef struct s2a_proto_ClientSessionStartReq s2a_proto_ClientSessionStartReq;
typedef struct s2a_proto_ServerSessionStartReq s2a_proto_ServerSessionStartReq;
typedef struct s2a_proto_SessionNextReq s2a_proto_SessionNextReq;
typedef struct s2a_proto_ResumptionTicketReq s2a_proto_ResumptionTicketReq;
typedef struct s2a_proto_SessionReq s2a_proto_SessionReq;
typedef struct s2a_proto_SessionState s2a_proto_SessionState;
typedef struct s2a_proto_SessionResult s2a_proto_SessionResult;
typedef struct s2a_proto_SessionStatus s2a_proto_SessionStatus;
typedef struct s2a_proto_SessionResp s2a_proto_SessionResp;
extern const upb_msglayout s2a_proto_AuthenticationMechanism_msginit;
extern const upb_msglayout s2a_proto_ClientSessionStartReq_msginit;
extern const upb_msglayout s2a_proto_ServerSessionStartReq_msginit;
extern const upb_msglayout s2a_proto_SessionNextReq_msginit;
extern const upb_msglayout s2a_proto_ResumptionTicketReq_msginit;
extern const upb_msglayout s2a_proto_SessionReq_msginit;
extern const upb_msglayout s2a_proto_SessionState_msginit;
extern const upb_msglayout s2a_proto_SessionResult_msginit;
extern const upb_msglayout s2a_proto_SessionStatus_msginit;
extern const upb_msglayout s2a_proto_SessionResp_msginit;
struct s2a_proto_Identity;
extern const upb_msglayout s2a_proto_Identity_msginit;


/* s2a.proto.AuthenticationMechanism */

UPB_INLINE s2a_proto_AuthenticationMechanism *s2a_proto_AuthenticationMechanism_new(upb_arena *arena) {
  return (s2a_proto_AuthenticationMechanism *)_upb_msg_new(&s2a_proto_AuthenticationMechanism_msginit, arena);
}
UPB_INLINE s2a_proto_AuthenticationMechanism *s2a_proto_AuthenticationMechanism_parse(const char *buf, size_t size,
                        upb_arena *arena) {
  s2a_proto_AuthenticationMechanism *ret = s2a_proto_AuthenticationMechanism_new(arena);
  return (ret && upb_decode(buf, size, ret, &s2a_proto_AuthenticationMechanism_msginit, arena)) ? ret : NULL;
}
UPB_INLINE s2a_proto_AuthenticationMechanism *s2a_proto_AuthenticationMechanism_parse_ex(const char *buf, size_t size,
                           upb_arena *arena, int options) {
  s2a_proto_AuthenticationMechanism *ret = s2a_proto_AuthenticationMechanism_new(arena);
  return (ret && _upb_decode(buf, size, ret, &s2a_proto_AuthenticationMechanism_msginit, arena, options))
      ? ret : NULL;
}
UPB_INLINE char *s2a_proto_AuthenticationMechanism_serialize(const s2a_proto_AuthenticationMechanism *msg, upb_arena *arena, size_t *len) {
  return upb_encode(msg, &s2a_proto_AuthenticationMechanism_msginit, arena, len);
}

typedef enum {
  s2a_proto_AuthenticationMechanism_mechanism_oneof_token = 2,
  s2a_proto_AuthenticationMechanism_mechanism_oneof_NOT_SET = 0
} s2a_proto_AuthenticationMechanism_mechanism_oneof_oneofcases;
UPB_INLINE s2a_proto_AuthenticationMechanism_mechanism_oneof_oneofcases s2a_proto_AuthenticationMechanism_mechanism_oneof_case(const s2a_proto_AuthenticationMechanism* msg) { return (s2a_proto_AuthenticationMechanism_mechanism_oneof_oneofcases)*UPB_PTR_AT(msg, UPB_SIZE(16, 32), int32_t); }

UPB_INLINE bool s2a_proto_AuthenticationMechanism_has_identity(const s2a_proto_AuthenticationMechanism *msg) { return _upb_hasbit(msg, 1); }
UPB_INLINE const struct s2a_proto_Identity* s2a_proto_AuthenticationMechanism_identity(const s2a_proto_AuthenticationMechanism *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(4, 8), const struct s2a_proto_Identity*); }
UPB_INLINE bool s2a_proto_AuthenticationMechanism_has_token(const s2a_proto_AuthenticationMechanism *msg) { return _upb_getoneofcase(msg, UPB_SIZE(16, 32)) == 2; }
UPB_INLINE upb_strview s2a_proto_AuthenticationMechanism_token(const s2a_proto_AuthenticationMechanism *msg) { return UPB_READ_ONEOF(msg, upb_strview, UPB_SIZE(8, 16), UPB_SIZE(16, 32), 2, upb_strview_make("", strlen(""))); }

UPB_INLINE void s2a_proto_AuthenticationMechanism_set_identity(s2a_proto_AuthenticationMechanism *msg, struct s2a_proto_Identity* value) {
  _upb_sethas(msg, 1);
  *UPB_PTR_AT(msg, UPB_SIZE(4, 8), struct s2a_proto_Identity*) = value;
}
UPB_INLINE struct s2a_proto_Identity* s2a_proto_AuthenticationMechanism_mutable_identity(s2a_proto_AuthenticationMechanism *msg, upb_arena *arena) {
  struct s2a_proto_Identity* sub = (struct s2a_proto_Identity*)s2a_proto_AuthenticationMechanism_identity(msg);
  if (sub == NULL) {
    sub = (struct s2a_proto_Identity*)_upb_msg_new(&s2a_proto_Identity_msginit, arena);
    if (!sub) return NULL;
    s2a_proto_AuthenticationMechanism_set_identity(msg, sub);
  }
  return sub;
}
UPB_INLINE void s2a_proto_AuthenticationMechanism_set_token(s2a_proto_AuthenticationMechanism *msg, upb_strview value) {
  UPB_WRITE_ONEOF(msg, upb_strview, UPB_SIZE(8, 16), value, UPB_SIZE(16, 32), 2);
}

/* s2a.proto.ClientSessionStartReq */

UPB_INLINE s2a_proto_ClientSessionStartReq *s2a_proto_ClientSessionStartReq_new(upb_arena *arena) {
  return (s2a_proto_ClientSessionStartReq *)_upb_msg_new(&s2a_proto_ClientSessionStartReq_msginit, arena);
}
UPB_INLINE s2a_proto_ClientSessionStartReq *s2a_proto_ClientSessionStartReq_parse(const char *buf, size_t size,
                        upb_arena *arena) {
  s2a_proto_ClientSessionStartReq *ret = s2a_proto_ClientSessionStartReq_new(arena);
  return (ret && upb_decode(buf, size, ret, &s2a_proto_ClientSessionStartReq_msginit, arena)) ? ret : NULL;
}
UPB_INLINE s2a_proto_ClientSessionStartReq *s2a_proto_ClientSessionStartReq_parse_ex(const char *buf, size_t size,
                           upb_arena *arena, int options) {
  s2a_proto_ClientSessionStartReq *ret = s2a_proto_ClientSessionStartReq_new(arena);
  return (ret && _upb_decode(buf, size, ret, &s2a_proto_ClientSessionStartReq_msginit, arena, options))
      ? ret : NULL;
}
UPB_INLINE char *s2a_proto_ClientSessionStartReq_serialize(const s2a_proto_ClientSessionStartReq *msg, upb_arena *arena, size_t *len) {
  return upb_encode(msg, &s2a_proto_ClientSessionStartReq_msginit, arena, len);
}

UPB_INLINE upb_strview const* s2a_proto_ClientSessionStartReq_application_protocols(const s2a_proto_ClientSessionStartReq *msg, size_t *len) { return (upb_strview const*)_upb_array_accessor(msg, UPB_SIZE(24, 40), len); }
UPB_INLINE int32_t s2a_proto_ClientSessionStartReq_min_tls_version(const s2a_proto_ClientSessionStartReq *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(4, 4), int32_t); }
UPB_INLINE int32_t s2a_proto_ClientSessionStartReq_max_tls_version(const s2a_proto_ClientSessionStartReq *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(8, 8), int32_t); }
UPB_INLINE int32_t const* s2a_proto_ClientSessionStartReq_tls_ciphersuites(const s2a_proto_ClientSessionStartReq *msg, size_t *len) { return (int32_t const*)_upb_array_accessor(msg, UPB_SIZE(28, 48), len); }
UPB_INLINE bool s2a_proto_ClientSessionStartReq_has_target_identities(const s2a_proto_ClientSessionStartReq *msg) { return _upb_has_submsg_nohasbit(msg, UPB_SIZE(32, 56)); }
UPB_INLINE const struct s2a_proto_Identity* const* s2a_proto_ClientSessionStartReq_target_identities(const s2a_proto_ClientSessionStartReq *msg, size_t *len) { return (const struct s2a_proto_Identity* const*)_upb_array_accessor(msg, UPB_SIZE(32, 56), len); }
UPB_INLINE bool s2a_proto_ClientSessionStartReq_has_local_identity(const s2a_proto_ClientSessionStartReq *msg) { return _upb_hasbit(msg, 1); }
UPB_INLINE const struct s2a_proto_Identity* s2a_proto_ClientSessionStartReq_local_identity(const s2a_proto_ClientSessionStartReq *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(20, 32), const struct s2a_proto_Identity*); }
UPB_INLINE upb_strview s2a_proto_ClientSessionStartReq_target_name(const s2a_proto_ClientSessionStartReq *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(12, 16), upb_strview); }

UPB_INLINE upb_strview* s2a_proto_ClientSessionStartReq_mutable_application_protocols(s2a_proto_ClientSessionStartReq *msg, size_t *len) {
  return (upb_strview*)_upb_array_mutable_accessor(msg, UPB_SIZE(24, 40), len);
}
UPB_INLINE upb_strview* s2a_proto_ClientSessionStartReq_resize_application_protocols(s2a_proto_ClientSessionStartReq *msg, size_t len, upb_arena *arena) {
  return (upb_strview*)_upb_array_resize_accessor2(msg, UPB_SIZE(24, 40), len, UPB_SIZE(3, 4), arena);
}
UPB_INLINE bool s2a_proto_ClientSessionStartReq_add_application_protocols(s2a_proto_ClientSessionStartReq *msg, upb_strview val, upb_arena *arena) {
  return _upb_array_append_accessor2(msg, UPB_SIZE(24, 40), UPB_SIZE(3, 4), &val,
      arena);
}
UPB_INLINE void s2a_proto_ClientSessionStartReq_set_min_tls_version(s2a_proto_ClientSessionStartReq *msg, int32_t value) {
  *UPB_PTR_AT(msg, UPB_SIZE(4, 4), int32_t) = value;
}
UPB_INLINE void s2a_proto_ClientSessionStartReq_set_max_tls_version(s2a_proto_ClientSessionStartReq *msg, int32_t value) {
  *UPB_PTR_AT(msg, UPB_SIZE(8, 8), int32_t) = value;
}
UPB_INLINE int32_t* s2a_proto_ClientSessionStartReq_mutable_tls_ciphersuites(s2a_proto_ClientSessionStartReq *msg, size_t *len) {
  return (int32_t*)_upb_array_mutable_accessor(msg, UPB_SIZE(28, 48), len);
}
UPB_INLINE int32_t* s2a_proto_ClientSessionStartReq_resize_tls_ciphersuites(s2a_proto_ClientSessionStartReq *msg, size_t len, upb_arena *arena) {
  return (int32_t*)_upb_array_resize_accessor2(msg, UPB_SIZE(28, 48), len, 2, arena);
}
UPB_INLINE bool s2a_proto_ClientSessionStartReq_add_tls_ciphersuites(s2a_proto_ClientSessionStartReq *msg, int32_t val, upb_arena *arena) {
  return _upb_array_append_accessor2(msg, UPB_SIZE(28, 48), 2, &val,
      arena);
}
UPB_INLINE struct s2a_proto_Identity** s2a_proto_ClientSessionStartReq_mutable_target_identities(s2a_proto_ClientSessionStartReq *msg, size_t *len) {
  return (struct s2a_proto_Identity**)_upb_array_mutable_accessor(msg, UPB_SIZE(32, 56), len);
}
UPB_INLINE struct s2a_proto_Identity** s2a_proto_ClientSessionStartReq_resize_target_identities(s2a_proto_ClientSessionStartReq *msg, size_t len, upb_arena *arena) {
  return (struct s2a_proto_Identity**)_upb_array_resize_accessor2(msg, UPB_SIZE(32, 56), len, UPB_SIZE(2, 3), arena);
}
UPB_INLINE struct s2a_proto_Identity* s2a_proto_ClientSessionStartReq_add_target_identities(s2a_proto_ClientSessionStartReq *msg, upb_arena *arena) {
  struct s2a_proto_Identity* sub = (struct s2a_proto_Identity*)_upb_msg_new(&s2a_proto_Identity_msginit, arena);
  bool ok = _upb_array_append_accessor2(
      msg, UPB_SIZE(32, 56), UPB_SIZE(2, 3), &sub, arena);
  if (!ok) return NULL;
  return sub;
}
UPB_INLINE void s2a_proto_ClientSessionStartReq_set_local_identity(s2a_proto_ClientSessionStartReq *msg, struct s2a_proto_Identity* value) {
  _upb_sethas(msg, 1);
  *UPB_PTR_AT(msg, UPB_SIZE(20, 32), struct s2a_proto_Identity*) = value;
}
UPB_INLINE struct s2a_proto_Identity* s2a_proto_ClientSessionStartReq_mutable_local_identity(s2a_proto_ClientSessionStartReq *msg, upb_arena *arena) {
  struct s2a_proto_Identity* sub = (struct s2a_proto_Identity*)s2a_proto_ClientSessionStartReq_local_identity(msg);
  if (sub == NULL) {
    sub = (struct s2a_proto_Identity*)_upb_msg_new(&s2a_proto_Identity_msginit, arena);
    if (!sub) return NULL;
    s2a_proto_ClientSessionStartReq_set_local_identity(msg, sub);
  }
  return sub;
}
UPB_INLINE void s2a_proto_ClientSessionStartReq_set_target_name(s2a_proto_ClientSessionStartReq *msg, upb_strview value) {
  *UPB_PTR_AT(msg, UPB_SIZE(12, 16), upb_strview) = value;
}

/* s2a.proto.ServerSessionStartReq */

UPB_INLINE s2a_proto_ServerSessionStartReq *s2a_proto_ServerSessionStartReq_new(upb_arena *arena) {
  return (s2a_proto_ServerSessionStartReq *)_upb_msg_new(&s2a_proto_ServerSessionStartReq_msginit, arena);
}
UPB_INLINE s2a_proto_ServerSessionStartReq *s2a_proto_ServerSessionStartReq_parse(const char *buf, size_t size,
                        upb_arena *arena) {
  s2a_proto_ServerSessionStartReq *ret = s2a_proto_ServerSessionStartReq_new(arena);
  return (ret && upb_decode(buf, size, ret, &s2a_proto_ServerSessionStartReq_msginit, arena)) ? ret : NULL;
}
UPB_INLINE s2a_proto_ServerSessionStartReq *s2a_proto_ServerSessionStartReq_parse_ex(const char *buf, size_t size,
                           upb_arena *arena, int options) {
  s2a_proto_ServerSessionStartReq *ret = s2a_proto_ServerSessionStartReq_new(arena);
  return (ret && _upb_decode(buf, size, ret, &s2a_proto_ServerSessionStartReq_msginit, arena, options))
      ? ret : NULL;
}
UPB_INLINE char *s2a_proto_ServerSessionStartReq_serialize(const s2a_proto_ServerSessionStartReq *msg, upb_arena *arena, size_t *len) {
  return upb_encode(msg, &s2a_proto_ServerSessionStartReq_msginit, arena, len);
}

UPB_INLINE upb_strview const* s2a_proto_ServerSessionStartReq_application_protocols(const s2a_proto_ServerSessionStartReq *msg, size_t *len) { return (upb_strview const*)_upb_array_accessor(msg, UPB_SIZE(16, 24), len); }
UPB_INLINE int32_t s2a_proto_ServerSessionStartReq_min_tls_version(const s2a_proto_ServerSessionStartReq *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(0, 0), int32_t); }
UPB_INLINE int32_t s2a_proto_ServerSessionStartReq_max_tls_version(const s2a_proto_ServerSessionStartReq *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(4, 4), int32_t); }
UPB_INLINE int32_t const* s2a_proto_ServerSessionStartReq_tls_ciphersuites(const s2a_proto_ServerSessionStartReq *msg, size_t *len) { return (int32_t const*)_upb_array_accessor(msg, UPB_SIZE(20, 32), len); }
UPB_INLINE bool s2a_proto_ServerSessionStartReq_has_local_identities(const s2a_proto_ServerSessionStartReq *msg) { return _upb_has_submsg_nohasbit(msg, UPB_SIZE(24, 40)); }
UPB_INLINE const struct s2a_proto_Identity* const* s2a_proto_ServerSessionStartReq_local_identities(const s2a_proto_ServerSessionStartReq *msg, size_t *len) { return (const struct s2a_proto_Identity* const*)_upb_array_accessor(msg, UPB_SIZE(24, 40), len); }
UPB_INLINE upb_strview s2a_proto_ServerSessionStartReq_in_bytes(const s2a_proto_ServerSessionStartReq *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(8, 8), upb_strview); }

UPB_INLINE upb_strview* s2a_proto_ServerSessionStartReq_mutable_application_protocols(s2a_proto_ServerSessionStartReq *msg, size_t *len) {
  return (upb_strview*)_upb_array_mutable_accessor(msg, UPB_SIZE(16, 24), len);
}
UPB_INLINE upb_strview* s2a_proto_ServerSessionStartReq_resize_application_protocols(s2a_proto_ServerSessionStartReq *msg, size_t len, upb_arena *arena) {
  return (upb_strview*)_upb_array_resize_accessor2(msg, UPB_SIZE(16, 24), len, UPB_SIZE(3, 4), arena);
}
UPB_INLINE bool s2a_proto_ServerSessionStartReq_add_application_protocols(s2a_proto_ServerSessionStartReq *msg, upb_strview val, upb_arena *arena) {
  return _upb_array_append_accessor2(msg, UPB_SIZE(16, 24), UPB_SIZE(3, 4), &val,
      arena);
}
UPB_INLINE void s2a_proto_ServerSessionStartReq_set_min_tls_version(s2a_proto_ServerSessionStartReq *msg, int32_t value) {
  *UPB_PTR_AT(msg, UPB_SIZE(0, 0), int32_t) = value;
}
UPB_INLINE void s2a_proto_ServerSessionStartReq_set_max_tls_version(s2a_proto_ServerSessionStartReq *msg, int32_t value) {
  *UPB_PTR_AT(msg, UPB_SIZE(4, 4), int32_t) = value;
}
UPB_INLINE int32_t* s2a_proto_ServerSessionStartReq_mutable_tls_ciphersuites(s2a_proto_ServerSessionStartReq *msg, size_t *len) {
  return (int32_t*)_upb_array_mutable_accessor(msg, UPB_SIZE(20, 32), len);
}
UPB_INLINE int32_t* s2a_proto_ServerSessionStartReq_resize_tls_ciphersuites(s2a_proto_ServerSessionStartReq *msg, size_t len, upb_arena *arena) {
  return (int32_t*)_upb_array_resize_accessor2(msg, UPB_SIZE(20, 32), len, 2, arena);
}
UPB_INLINE bool s2a_proto_ServerSessionStartReq_add_tls_ciphersuites(s2a_proto_ServerSessionStartReq *msg, int32_t val, upb_arena *arena) {
  return _upb_array_append_accessor2(msg, UPB_SIZE(20, 32), 2, &val,
      arena);
}
UPB_INLINE struct s2a_proto_Identity** s2a_proto_ServerSessionStartReq_mutable_local_identities(s2a_proto_ServerSessionStartReq *msg, size_t *len) {
  return (struct s2a_proto_Identity**)_upb_array_mutable_accessor(msg, UPB_SIZE(24, 40), len);
}
UPB_INLINE struct s2a_proto_Identity** s2a_proto_ServerSessionStartReq_resize_local_identities(s2a_proto_ServerSessionStartReq *msg, size_t len, upb_arena *arena) {
  return (struct s2a_proto_Identity**)_upb_array_resize_accessor2(msg, UPB_SIZE(24, 40), len, UPB_SIZE(2, 3), arena);
}
UPB_INLINE struct s2a_proto_Identity* s2a_proto_ServerSessionStartReq_add_local_identities(s2a_proto_ServerSessionStartReq *msg, upb_arena *arena) {
  struct s2a_proto_Identity* sub = (struct s2a_proto_Identity*)_upb_msg_new(&s2a_proto_Identity_msginit, arena);
  bool ok = _upb_array_append_accessor2(
      msg, UPB_SIZE(24, 40), UPB_SIZE(2, 3), &sub, arena);
  if (!ok) return NULL;
  return sub;
}
UPB_INLINE void s2a_proto_ServerSessionStartReq_set_in_bytes(s2a_proto_ServerSessionStartReq *msg, upb_strview value) {
  *UPB_PTR_AT(msg, UPB_SIZE(8, 8), upb_strview) = value;
}

/* s2a.proto.SessionNextReq */

UPB_INLINE s2a_proto_SessionNextReq *s2a_proto_SessionNextReq_new(upb_arena *arena) {
  return (s2a_proto_SessionNextReq *)_upb_msg_new(&s2a_proto_SessionNextReq_msginit, arena);
}
UPB_INLINE s2a_proto_SessionNextReq *s2a_proto_SessionNextReq_parse(const char *buf, size_t size,
                        upb_arena *arena) {
  s2a_proto_SessionNextReq *ret = s2a_proto_SessionNextReq_new(arena);
  return (ret && upb_decode(buf, size, ret, &s2a_proto_SessionNextReq_msginit, arena)) ? ret : NULL;
}
UPB_INLINE s2a_proto_SessionNextReq *s2a_proto_SessionNextReq_parse_ex(const char *buf, size_t size,
                           upb_arena *arena, int options) {
  s2a_proto_SessionNextReq *ret = s2a_proto_SessionNextReq_new(arena);
  return (ret && _upb_decode(buf, size, ret, &s2a_proto_SessionNextReq_msginit, arena, options))
      ? ret : NULL;
}
UPB_INLINE char *s2a_proto_SessionNextReq_serialize(const s2a_proto_SessionNextReq *msg, upb_arena *arena, size_t *len) {
  return upb_encode(msg, &s2a_proto_SessionNextReq_msginit, arena, len);
}

UPB_INLINE upb_strview s2a_proto_SessionNextReq_in_bytes(const s2a_proto_SessionNextReq *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(0, 0), upb_strview); }

UPB_INLINE void s2a_proto_SessionNextReq_set_in_bytes(s2a_proto_SessionNextReq *msg, upb_strview value) {
  *UPB_PTR_AT(msg, UPB_SIZE(0, 0), upb_strview) = value;
}

/* s2a.proto.ResumptionTicketReq */

UPB_INLINE s2a_proto_ResumptionTicketReq *s2a_proto_ResumptionTicketReq_new(upb_arena *arena) {
  return (s2a_proto_ResumptionTicketReq *)_upb_msg_new(&s2a_proto_ResumptionTicketReq_msginit, arena);
}
UPB_INLINE s2a_proto_ResumptionTicketReq *s2a_proto_ResumptionTicketReq_parse(const char *buf, size_t size,
                        upb_arena *arena) {
  s2a_proto_ResumptionTicketReq *ret = s2a_proto_ResumptionTicketReq_new(arena);
  return (ret && upb_decode(buf, size, ret, &s2a_proto_ResumptionTicketReq_msginit, arena)) ? ret : NULL;
}
UPB_INLINE s2a_proto_ResumptionTicketReq *s2a_proto_ResumptionTicketReq_parse_ex(const char *buf, size_t size,
                           upb_arena *arena, int options) {
  s2a_proto_ResumptionTicketReq *ret = s2a_proto_ResumptionTicketReq_new(arena);
  return (ret && _upb_decode(buf, size, ret, &s2a_proto_ResumptionTicketReq_msginit, arena, options))
      ? ret : NULL;
}
UPB_INLINE char *s2a_proto_ResumptionTicketReq_serialize(const s2a_proto_ResumptionTicketReq *msg, upb_arena *arena, size_t *len) {
  return upb_encode(msg, &s2a_proto_ResumptionTicketReq_msginit, arena, len);
}

UPB_INLINE upb_strview const* s2a_proto_ResumptionTicketReq_in_bytes(const s2a_proto_ResumptionTicketReq *msg, size_t *len) { return (upb_strview const*)_upb_array_accessor(msg, UPB_SIZE(20, 24), len); }
UPB_INLINE uint64_t s2a_proto_ResumptionTicketReq_connection_id(const s2a_proto_ResumptionTicketReq *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(8, 8), uint64_t); }
UPB_INLINE bool s2a_proto_ResumptionTicketReq_has_local_identity(const s2a_proto_ResumptionTicketReq *msg) { return _upb_hasbit(msg, 1); }
UPB_INLINE const struct s2a_proto_Identity* s2a_proto_ResumptionTicketReq_local_identity(const s2a_proto_ResumptionTicketReq *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(16, 16), const struct s2a_proto_Identity*); }

UPB_INLINE upb_strview* s2a_proto_ResumptionTicketReq_mutable_in_bytes(s2a_proto_ResumptionTicketReq *msg, size_t *len) {
  return (upb_strview*)_upb_array_mutable_accessor(msg, UPB_SIZE(20, 24), len);
}
UPB_INLINE upb_strview* s2a_proto_ResumptionTicketReq_resize_in_bytes(s2a_proto_ResumptionTicketReq *msg, size_t len, upb_arena *arena) {
  return (upb_strview*)_upb_array_resize_accessor2(msg, UPB_SIZE(20, 24), len, UPB_SIZE(3, 4), arena);
}
UPB_INLINE bool s2a_proto_ResumptionTicketReq_add_in_bytes(s2a_proto_ResumptionTicketReq *msg, upb_strview val, upb_arena *arena) {
  return _upb_array_append_accessor2(msg, UPB_SIZE(20, 24), UPB_SIZE(3, 4), &val,
      arena);
}
UPB_INLINE void s2a_proto_ResumptionTicketReq_set_connection_id(s2a_proto_ResumptionTicketReq *msg, uint64_t value) {
  *UPB_PTR_AT(msg, UPB_SIZE(8, 8), uint64_t) = value;
}
UPB_INLINE void s2a_proto_ResumptionTicketReq_set_local_identity(s2a_proto_ResumptionTicketReq *msg, struct s2a_proto_Identity* value) {
  _upb_sethas(msg, 1);
  *UPB_PTR_AT(msg, UPB_SIZE(16, 16), struct s2a_proto_Identity*) = value;
}
UPB_INLINE struct s2a_proto_Identity* s2a_proto_ResumptionTicketReq_mutable_local_identity(s2a_proto_ResumptionTicketReq *msg, upb_arena *arena) {
  struct s2a_proto_Identity* sub = (struct s2a_proto_Identity*)s2a_proto_ResumptionTicketReq_local_identity(msg);
  if (sub == NULL) {
    sub = (struct s2a_proto_Identity*)_upb_msg_new(&s2a_proto_Identity_msginit, arena);
    if (!sub) return NULL;
    s2a_proto_ResumptionTicketReq_set_local_identity(msg, sub);
  }
  return sub;
}

/* s2a.proto.SessionReq */

UPB_INLINE s2a_proto_SessionReq *s2a_proto_SessionReq_new(upb_arena *arena) {
  return (s2a_proto_SessionReq *)_upb_msg_new(&s2a_proto_SessionReq_msginit, arena);
}
UPB_INLINE s2a_proto_SessionReq *s2a_proto_SessionReq_parse(const char *buf, size_t size,
                        upb_arena *arena) {
  s2a_proto_SessionReq *ret = s2a_proto_SessionReq_new(arena);
  return (ret && upb_decode(buf, size, ret, &s2a_proto_SessionReq_msginit, arena)) ? ret : NULL;
}
UPB_INLINE s2a_proto_SessionReq *s2a_proto_SessionReq_parse_ex(const char *buf, size_t size,
                           upb_arena *arena, int options) {
  s2a_proto_SessionReq *ret = s2a_proto_SessionReq_new(arena);
  return (ret && _upb_decode(buf, size, ret, &s2a_proto_SessionReq_msginit, arena, options))
      ? ret : NULL;
}
UPB_INLINE char *s2a_proto_SessionReq_serialize(const s2a_proto_SessionReq *msg, upb_arena *arena, size_t *len) {
  return upb_encode(msg, &s2a_proto_SessionReq_msginit, arena, len);
}

typedef enum {
  s2a_proto_SessionReq_req_oneof_client_start = 1,
  s2a_proto_SessionReq_req_oneof_server_start = 2,
  s2a_proto_SessionReq_req_oneof_next = 3,
  s2a_proto_SessionReq_req_oneof_resumption_ticket = 4,
  s2a_proto_SessionReq_req_oneof_NOT_SET = 0
} s2a_proto_SessionReq_req_oneof_oneofcases;
UPB_INLINE s2a_proto_SessionReq_req_oneof_oneofcases s2a_proto_SessionReq_req_oneof_case(const s2a_proto_SessionReq* msg) { return (s2a_proto_SessionReq_req_oneof_oneofcases)*UPB_PTR_AT(msg, UPB_SIZE(8, 16), int32_t); }

UPB_INLINE bool s2a_proto_SessionReq_has_client_start(const s2a_proto_SessionReq *msg) { return _upb_getoneofcase(msg, UPB_SIZE(8, 16)) == 1; }
UPB_INLINE const s2a_proto_ClientSessionStartReq* s2a_proto_SessionReq_client_start(const s2a_proto_SessionReq *msg) { return UPB_READ_ONEOF(msg, const s2a_proto_ClientSessionStartReq*, UPB_SIZE(4, 8), UPB_SIZE(8, 16), 1, NULL); }
UPB_INLINE bool s2a_proto_SessionReq_has_server_start(const s2a_proto_SessionReq *msg) { return _upb_getoneofcase(msg, UPB_SIZE(8, 16)) == 2; }
UPB_INLINE const s2a_proto_ServerSessionStartReq* s2a_proto_SessionReq_server_start(const s2a_proto_SessionReq *msg) { return UPB_READ_ONEOF(msg, const s2a_proto_ServerSessionStartReq*, UPB_SIZE(4, 8), UPB_SIZE(8, 16), 2, NULL); }
UPB_INLINE bool s2a_proto_SessionReq_has_next(const s2a_proto_SessionReq *msg) { return _upb_getoneofcase(msg, UPB_SIZE(8, 16)) == 3; }
UPB_INLINE const s2a_proto_SessionNextReq* s2a_proto_SessionReq_next(const s2a_proto_SessionReq *msg) { return UPB_READ_ONEOF(msg, const s2a_proto_SessionNextReq*, UPB_SIZE(4, 8), UPB_SIZE(8, 16), 3, NULL); }
UPB_INLINE bool s2a_proto_SessionReq_has_resumption_ticket(const s2a_proto_SessionReq *msg) { return _upb_getoneofcase(msg, UPB_SIZE(8, 16)) == 4; }
UPB_INLINE const s2a_proto_ResumptionTicketReq* s2a_proto_SessionReq_resumption_ticket(const s2a_proto_SessionReq *msg) { return UPB_READ_ONEOF(msg, const s2a_proto_ResumptionTicketReq*, UPB_SIZE(4, 8), UPB_SIZE(8, 16), 4, NULL); }
UPB_INLINE bool s2a_proto_SessionReq_has_auth_mechanisms(const s2a_proto_SessionReq *msg) { return _upb_has_submsg_nohasbit(msg, UPB_SIZE(0, 0)); }
UPB_INLINE const s2a_proto_AuthenticationMechanism* const* s2a_proto_SessionReq_auth_mechanisms(const s2a_proto_SessionReq *msg, size_t *len) { return (const s2a_proto_AuthenticationMechanism* const*)_upb_array_accessor(msg, UPB_SIZE(0, 0), len); }

UPB_INLINE void s2a_proto_SessionReq_set_client_start(s2a_proto_SessionReq *msg, s2a_proto_ClientSessionStartReq* value) {
  UPB_WRITE_ONEOF(msg, s2a_proto_ClientSessionStartReq*, UPB_SIZE(4, 8), value, UPB_SIZE(8, 16), 1);
}
UPB_INLINE struct s2a_proto_ClientSessionStartReq* s2a_proto_SessionReq_mutable_client_start(s2a_proto_SessionReq *msg, upb_arena *arena) {
  struct s2a_proto_ClientSessionStartReq* sub = (struct s2a_proto_ClientSessionStartReq*)s2a_proto_SessionReq_client_start(msg);
  if (sub == NULL) {
    sub = (struct s2a_proto_ClientSessionStartReq*)_upb_msg_new(&s2a_proto_ClientSessionStartReq_msginit, arena);
    if (!sub) return NULL;
    s2a_proto_SessionReq_set_client_start(msg, sub);
  }
  return sub;
}
UPB_INLINE void s2a_proto_SessionReq_set_server_start(s2a_proto_SessionReq *msg, s2a_proto_ServerSessionStartReq* value) {
  UPB_WRITE_ONEOF(msg, s2a_proto_ServerSessionStartReq*, UPB_SIZE(4, 8), value, UPB_SIZE(8, 16), 2);
}
UPB_INLINE struct s2a_proto_ServerSessionStartReq* s2a_proto_SessionReq_mutable_server_start(s2a_proto_SessionReq *msg, upb_arena *arena) {
  struct s2a_proto_ServerSessionStartReq* sub = (struct s2a_proto_ServerSessionStartReq*)s2a_proto_SessionReq_server_start(msg);
  if (sub == NULL) {
    sub = (struct s2a_proto_ServerSessionStartReq*)_upb_msg_new(&s2a_proto_ServerSessionStartReq_msginit, arena);
    if (!sub) return NULL;
    s2a_proto_SessionReq_set_server_start(msg, sub);
  }
  return sub;
}
UPB_INLINE void s2a_proto_SessionReq_set_next(s2a_proto_SessionReq *msg, s2a_proto_SessionNextReq* value) {
  UPB_WRITE_ONEOF(msg, s2a_proto_SessionNextReq*, UPB_SIZE(4, 8), value, UPB_SIZE(8, 16), 3);
}
UPB_INLINE struct s2a_proto_SessionNextReq* s2a_proto_SessionReq_mutable_next(s2a_proto_SessionReq *msg, upb_arena *arena) {
  struct s2a_proto_SessionNextReq* sub = (struct s2a_proto_SessionNextReq*)s2a_proto_SessionReq_next(msg);
  if (sub == NULL) {
    sub = (struct s2a_proto_SessionNextReq*)_upb_msg_new(&s2a_proto_SessionNextReq_msginit, arena);
    if (!sub) return NULL;
    s2a_proto_SessionReq_set_next(msg, sub);
  }
  return sub;
}
UPB_INLINE void s2a_proto_SessionReq_set_resumption_ticket(s2a_proto_SessionReq *msg, s2a_proto_ResumptionTicketReq* value) {
  UPB_WRITE_ONEOF(msg, s2a_proto_ResumptionTicketReq*, UPB_SIZE(4, 8), value, UPB_SIZE(8, 16), 4);
}
UPB_INLINE struct s2a_proto_ResumptionTicketReq* s2a_proto_SessionReq_mutable_resumption_ticket(s2a_proto_SessionReq *msg, upb_arena *arena) {
  struct s2a_proto_ResumptionTicketReq* sub = (struct s2a_proto_ResumptionTicketReq*)s2a_proto_SessionReq_resumption_ticket(msg);
  if (sub == NULL) {
    sub = (struct s2a_proto_ResumptionTicketReq*)_upb_msg_new(&s2a_proto_ResumptionTicketReq_msginit, arena);
    if (!sub) return NULL;
    s2a_proto_SessionReq_set_resumption_ticket(msg, sub);
  }
  return sub;
}
UPB_INLINE s2a_proto_AuthenticationMechanism** s2a_proto_SessionReq_mutable_auth_mechanisms(s2a_proto_SessionReq *msg, size_t *len) {
  return (s2a_proto_AuthenticationMechanism**)_upb_array_mutable_accessor(msg, UPB_SIZE(0, 0), len);
}
UPB_INLINE s2a_proto_AuthenticationMechanism** s2a_proto_SessionReq_resize_auth_mechanisms(s2a_proto_SessionReq *msg, size_t len, upb_arena *arena) {
  return (s2a_proto_AuthenticationMechanism**)_upb_array_resize_accessor2(msg, UPB_SIZE(0, 0), len, UPB_SIZE(2, 3), arena);
}
UPB_INLINE struct s2a_proto_AuthenticationMechanism* s2a_proto_SessionReq_add_auth_mechanisms(s2a_proto_SessionReq *msg, upb_arena *arena) {
  struct s2a_proto_AuthenticationMechanism* sub = (struct s2a_proto_AuthenticationMechanism*)_upb_msg_new(&s2a_proto_AuthenticationMechanism_msginit, arena);
  bool ok = _upb_array_append_accessor2(
      msg, UPB_SIZE(0, 0), UPB_SIZE(2, 3), &sub, arena);
  if (!ok) return NULL;
  return sub;
}

/* s2a.proto.SessionState */

UPB_INLINE s2a_proto_SessionState *s2a_proto_SessionState_new(upb_arena *arena) {
  return (s2a_proto_SessionState *)_upb_msg_new(&s2a_proto_SessionState_msginit, arena);
}
UPB_INLINE s2a_proto_SessionState *s2a_proto_SessionState_parse(const char *buf, size_t size,
                        upb_arena *arena) {
  s2a_proto_SessionState *ret = s2a_proto_SessionState_new(arena);
  return (ret && upb_decode(buf, size, ret, &s2a_proto_SessionState_msginit, arena)) ? ret : NULL;
}
UPB_INLINE s2a_proto_SessionState *s2a_proto_SessionState_parse_ex(const char *buf, size_t size,
                           upb_arena *arena, int options) {
  s2a_proto_SessionState *ret = s2a_proto_SessionState_new(arena);
  return (ret && _upb_decode(buf, size, ret, &s2a_proto_SessionState_msginit, arena, options))
      ? ret : NULL;
}
UPB_INLINE char *s2a_proto_SessionState_serialize(const s2a_proto_SessionState *msg, upb_arena *arena, size_t *len) {
  return upb_encode(msg, &s2a_proto_SessionState_msginit, arena, len);
}

UPB_INLINE int32_t s2a_proto_SessionState_tls_version(const s2a_proto_SessionState *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(0, 0), int32_t); }
UPB_INLINE int32_t s2a_proto_SessionState_tls_ciphersuite(const s2a_proto_SessionState *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(4, 4), int32_t); }
UPB_INLINE uint64_t s2a_proto_SessionState_in_sequence(const s2a_proto_SessionState *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(8, 8), uint64_t); }
UPB_INLINE uint64_t s2a_proto_SessionState_out_sequence(const s2a_proto_SessionState *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(16, 16), uint64_t); }
UPB_INLINE upb_strview s2a_proto_SessionState_in_key(const s2a_proto_SessionState *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(36, 40), upb_strview); }
UPB_INLINE upb_strview s2a_proto_SessionState_out_key(const s2a_proto_SessionState *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(44, 56), upb_strview); }
UPB_INLINE upb_strview s2a_proto_SessionState_in_fixed_nonce(const s2a_proto_SessionState *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(52, 72), upb_strview); }
UPB_INLINE upb_strview s2a_proto_SessionState_out_fixed_nonce(const s2a_proto_SessionState *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(60, 88), upb_strview); }
UPB_INLINE uint64_t s2a_proto_SessionState_connection_id(const s2a_proto_SessionState *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(24, 24), uint64_t); }
UPB_INLINE bool s2a_proto_SessionState_is_handshake_resumed(const s2a_proto_SessionState *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(32, 32), bool); }

UPB_INLINE void s2a_proto_SessionState_set_tls_version(s2a_proto_SessionState *msg, int32_t value) {
  *UPB_PTR_AT(msg, UPB_SIZE(0, 0), int32_t) = value;
}
UPB_INLINE void s2a_proto_SessionState_set_tls_ciphersuite(s2a_proto_SessionState *msg, int32_t value) {
  *UPB_PTR_AT(msg, UPB_SIZE(4, 4), int32_t) = value;
}
UPB_INLINE void s2a_proto_SessionState_set_in_sequence(s2a_proto_SessionState *msg, uint64_t value) {
  *UPB_PTR_AT(msg, UPB_SIZE(8, 8), uint64_t) = value;
}
UPB_INLINE void s2a_proto_SessionState_set_out_sequence(s2a_proto_SessionState *msg, uint64_t value) {
  *UPB_PTR_AT(msg, UPB_SIZE(16, 16), uint64_t) = value;
}
UPB_INLINE void s2a_proto_SessionState_set_in_key(s2a_proto_SessionState *msg, upb_strview value) {
  *UPB_PTR_AT(msg, UPB_SIZE(36, 40), upb_strview) = value;
}
UPB_INLINE void s2a_proto_SessionState_set_out_key(s2a_proto_SessionState *msg, upb_strview value) {
  *UPB_PTR_AT(msg, UPB_SIZE(44, 56), upb_strview) = value;
}
UPB_INLINE void s2a_proto_SessionState_set_in_fixed_nonce(s2a_proto_SessionState *msg, upb_strview value) {
  *UPB_PTR_AT(msg, UPB_SIZE(52, 72), upb_strview) = value;
}
UPB_INLINE void s2a_proto_SessionState_set_out_fixed_nonce(s2a_proto_SessionState *msg, upb_strview value) {
  *UPB_PTR_AT(msg, UPB_SIZE(60, 88), upb_strview) = value;
}
UPB_INLINE void s2a_proto_SessionState_set_connection_id(s2a_proto_SessionState *msg, uint64_t value) {
  *UPB_PTR_AT(msg, UPB_SIZE(24, 24), uint64_t) = value;
}
UPB_INLINE void s2a_proto_SessionState_set_is_handshake_resumed(s2a_proto_SessionState *msg, bool value) {
  *UPB_PTR_AT(msg, UPB_SIZE(32, 32), bool) = value;
}

/* s2a.proto.SessionResult */

UPB_INLINE s2a_proto_SessionResult *s2a_proto_SessionResult_new(upb_arena *arena) {
  return (s2a_proto_SessionResult *)_upb_msg_new(&s2a_proto_SessionResult_msginit, arena);
}
UPB_INLINE s2a_proto_SessionResult *s2a_proto_SessionResult_parse(const char *buf, size_t size,
                        upb_arena *arena) {
  s2a_proto_SessionResult *ret = s2a_proto_SessionResult_new(arena);
  return (ret && upb_decode(buf, size, ret, &s2a_proto_SessionResult_msginit, arena)) ? ret : NULL;
}
UPB_INLINE s2a_proto_SessionResult *s2a_proto_SessionResult_parse_ex(const char *buf, size_t size,
                           upb_arena *arena, int options) {
  s2a_proto_SessionResult *ret = s2a_proto_SessionResult_new(arena);
  return (ret && _upb_decode(buf, size, ret, &s2a_proto_SessionResult_msginit, arena, options))
      ? ret : NULL;
}
UPB_INLINE char *s2a_proto_SessionResult_serialize(const s2a_proto_SessionResult *msg, upb_arena *arena, size_t *len) {
  return upb_encode(msg, &s2a_proto_SessionResult_msginit, arena, len);
}

UPB_INLINE upb_strview s2a_proto_SessionResult_application_protocol(const s2a_proto_SessionResult *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(4, 8), upb_strview); }
UPB_INLINE bool s2a_proto_SessionResult_has_state(const s2a_proto_SessionResult *msg) { return _upb_hasbit(msg, 1); }
UPB_INLINE const s2a_proto_SessionState* s2a_proto_SessionResult_state(const s2a_proto_SessionResult *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(28, 56), const s2a_proto_SessionState*); }
UPB_INLINE bool s2a_proto_SessionResult_has_peer_identity(const s2a_proto_SessionResult *msg) { return _upb_hasbit(msg, 2); }
UPB_INLINE const struct s2a_proto_Identity* s2a_proto_SessionResult_peer_identity(const s2a_proto_SessionResult *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(32, 64), const struct s2a_proto_Identity*); }
UPB_INLINE bool s2a_proto_SessionResult_has_local_identity(const s2a_proto_SessionResult *msg) { return _upb_hasbit(msg, 3); }
UPB_INLINE const struct s2a_proto_Identity* s2a_proto_SessionResult_local_identity(const s2a_proto_SessionResult *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(36, 72), const struct s2a_proto_Identity*); }
UPB_INLINE upb_strview s2a_proto_SessionResult_local_cert_fingerprint(const s2a_proto_SessionResult *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(12, 24), upb_strview); }
UPB_INLINE upb_strview s2a_proto_SessionResult_peer_cert_fingerprint(const s2a_proto_SessionResult *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(20, 40), upb_strview); }

UPB_INLINE void s2a_proto_SessionResult_set_application_protocol(s2a_proto_SessionResult *msg, upb_strview value) {
  *UPB_PTR_AT(msg, UPB_SIZE(4, 8), upb_strview) = value;
}
UPB_INLINE void s2a_proto_SessionResult_set_state(s2a_proto_SessionResult *msg, s2a_proto_SessionState* value) {
  _upb_sethas(msg, 1);
  *UPB_PTR_AT(msg, UPB_SIZE(28, 56), s2a_proto_SessionState*) = value;
}
UPB_INLINE struct s2a_proto_SessionState* s2a_proto_SessionResult_mutable_state(s2a_proto_SessionResult *msg, upb_arena *arena) {
  struct s2a_proto_SessionState* sub = (struct s2a_proto_SessionState*)s2a_proto_SessionResult_state(msg);
  if (sub == NULL) {
    sub = (struct s2a_proto_SessionState*)_upb_msg_new(&s2a_proto_SessionState_msginit, arena);
    if (!sub) return NULL;
    s2a_proto_SessionResult_set_state(msg, sub);
  }
  return sub;
}
UPB_INLINE void s2a_proto_SessionResult_set_peer_identity(s2a_proto_SessionResult *msg, struct s2a_proto_Identity* value) {
  _upb_sethas(msg, 2);
  *UPB_PTR_AT(msg, UPB_SIZE(32, 64), struct s2a_proto_Identity*) = value;
}
UPB_INLINE struct s2a_proto_Identity* s2a_proto_SessionResult_mutable_peer_identity(s2a_proto_SessionResult *msg, upb_arena *arena) {
  struct s2a_proto_Identity* sub = (struct s2a_proto_Identity*)s2a_proto_SessionResult_peer_identity(msg);
  if (sub == NULL) {
    sub = (struct s2a_proto_Identity*)_upb_msg_new(&s2a_proto_Identity_msginit, arena);
    if (!sub) return NULL;
    s2a_proto_SessionResult_set_peer_identity(msg, sub);
  }
  return sub;
}
UPB_INLINE void s2a_proto_SessionResult_set_local_identity(s2a_proto_SessionResult *msg, struct s2a_proto_Identity* value) {
  _upb_sethas(msg, 3);
  *UPB_PTR_AT(msg, UPB_SIZE(36, 72), struct s2a_proto_Identity*) = value;
}
UPB_INLINE struct s2a_proto_Identity* s2a_proto_SessionResult_mutable_local_identity(s2a_proto_SessionResult *msg, upb_arena *arena) {
  struct s2a_proto_Identity* sub = (struct s2a_proto_Identity*)s2a_proto_SessionResult_local_identity(msg);
  if (sub == NULL) {
    sub = (struct s2a_proto_Identity*)_upb_msg_new(&s2a_proto_Identity_msginit, arena);
    if (!sub) return NULL;
    s2a_proto_SessionResult_set_local_identity(msg, sub);
  }
  return sub;
}
UPB_INLINE void s2a_proto_SessionResult_set_local_cert_fingerprint(s2a_proto_SessionResult *msg, upb_strview value) {
  *UPB_PTR_AT(msg, UPB_SIZE(12, 24), upb_strview) = value;
}
UPB_INLINE void s2a_proto_SessionResult_set_peer_cert_fingerprint(s2a_proto_SessionResult *msg, upb_strview value) {
  *UPB_PTR_AT(msg, UPB_SIZE(20, 40), upb_strview) = value;
}

/* s2a.proto.SessionStatus */

UPB_INLINE s2a_proto_SessionStatus *s2a_proto_SessionStatus_new(upb_arena *arena) {
  return (s2a_proto_SessionStatus *)_upb_msg_new(&s2a_proto_SessionStatus_msginit, arena);
}
UPB_INLINE s2a_proto_SessionStatus *s2a_proto_SessionStatus_parse(const char *buf, size_t size,
                        upb_arena *arena) {
  s2a_proto_SessionStatus *ret = s2a_proto_SessionStatus_new(arena);
  return (ret && upb_decode(buf, size, ret, &s2a_proto_SessionStatus_msginit, arena)) ? ret : NULL;
}
UPB_INLINE s2a_proto_SessionStatus *s2a_proto_SessionStatus_parse_ex(const char *buf, size_t size,
                           upb_arena *arena, int options) {
  s2a_proto_SessionStatus *ret = s2a_proto_SessionStatus_new(arena);
  return (ret && _upb_decode(buf, size, ret, &s2a_proto_SessionStatus_msginit, arena, options))
      ? ret : NULL;
}
UPB_INLINE char *s2a_proto_SessionStatus_serialize(const s2a_proto_SessionStatus *msg, upb_arena *arena, size_t *len) {
  return upb_encode(msg, &s2a_proto_SessionStatus_msginit, arena, len);
}

UPB_INLINE uint32_t s2a_proto_SessionStatus_code(const s2a_proto_SessionStatus *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(0, 0), uint32_t); }
UPB_INLINE upb_strview s2a_proto_SessionStatus_details(const s2a_proto_SessionStatus *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(4, 8), upb_strview); }

UPB_INLINE void s2a_proto_SessionStatus_set_code(s2a_proto_SessionStatus *msg, uint32_t value) {
  *UPB_PTR_AT(msg, UPB_SIZE(0, 0), uint32_t) = value;
}
UPB_INLINE void s2a_proto_SessionStatus_set_details(s2a_proto_SessionStatus *msg, upb_strview value) {
  *UPB_PTR_AT(msg, UPB_SIZE(4, 8), upb_strview) = value;
}

/* s2a.proto.SessionResp */

UPB_INLINE s2a_proto_SessionResp *s2a_proto_SessionResp_new(upb_arena *arena) {
  return (s2a_proto_SessionResp *)_upb_msg_new(&s2a_proto_SessionResp_msginit, arena);
}
UPB_INLINE s2a_proto_SessionResp *s2a_proto_SessionResp_parse(const char *buf, size_t size,
                        upb_arena *arena) {
  s2a_proto_SessionResp *ret = s2a_proto_SessionResp_new(arena);
  return (ret && upb_decode(buf, size, ret, &s2a_proto_SessionResp_msginit, arena)) ? ret : NULL;
}
UPB_INLINE s2a_proto_SessionResp *s2a_proto_SessionResp_parse_ex(const char *buf, size_t size,
                           upb_arena *arena, int options) {
  s2a_proto_SessionResp *ret = s2a_proto_SessionResp_new(arena);
  return (ret && _upb_decode(buf, size, ret, &s2a_proto_SessionResp_msginit, arena, options))
      ? ret : NULL;
}
UPB_INLINE char *s2a_proto_SessionResp_serialize(const s2a_proto_SessionResp *msg, upb_arena *arena, size_t *len) {
  return upb_encode(msg, &s2a_proto_SessionResp_msginit, arena, len);
}

UPB_INLINE bool s2a_proto_SessionResp_has_local_identity(const s2a_proto_SessionResp *msg) { return _upb_hasbit(msg, 1); }
UPB_INLINE const struct s2a_proto_Identity* s2a_proto_SessionResp_local_identity(const s2a_proto_SessionResp *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(16, 24), const struct s2a_proto_Identity*); }
UPB_INLINE upb_strview s2a_proto_SessionResp_out_frames(const s2a_proto_SessionResp *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(8, 8), upb_strview); }
UPB_INLINE uint32_t s2a_proto_SessionResp_bytes_consumed(const s2a_proto_SessionResp *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(4, 4), uint32_t); }
UPB_INLINE bool s2a_proto_SessionResp_has_result(const s2a_proto_SessionResp *msg) { return _upb_hasbit(msg, 2); }
UPB_INLINE const s2a_proto_SessionResult* s2a_proto_SessionResp_result(const s2a_proto_SessionResp *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(20, 32), const s2a_proto_SessionResult*); }
UPB_INLINE bool s2a_proto_SessionResp_has_status(const s2a_proto_SessionResp *msg) { return _upb_hasbit(msg, 3); }
UPB_INLINE const s2a_proto_SessionStatus* s2a_proto_SessionResp_status(const s2a_proto_SessionResp *msg) { return *UPB_PTR_AT(msg, UPB_SIZE(24, 40), const s2a_proto_SessionStatus*); }

UPB_INLINE void s2a_proto_SessionResp_set_local_identity(s2a_proto_SessionResp *msg, struct s2a_proto_Identity* value) {
  _upb_sethas(msg, 1);
  *UPB_PTR_AT(msg, UPB_SIZE(16, 24), struct s2a_proto_Identity*) = value;
}
UPB_INLINE struct s2a_proto_Identity* s2a_proto_SessionResp_mutable_local_identity(s2a_proto_SessionResp *msg, upb_arena *arena) {
  struct s2a_proto_Identity* sub = (struct s2a_proto_Identity*)s2a_proto_SessionResp_local_identity(msg);
  if (sub == NULL) {
    sub = (struct s2a_proto_Identity*)_upb_msg_new(&s2a_proto_Identity_msginit, arena);
    if (!sub) return NULL;
    s2a_proto_SessionResp_set_local_identity(msg, sub);
  }
  return sub;
}
UPB_INLINE void s2a_proto_SessionResp_set_out_frames(s2a_proto_SessionResp *msg, upb_strview value) {
  *UPB_PTR_AT(msg, UPB_SIZE(8, 8), upb_strview) = value;
}
UPB_INLINE void s2a_proto_SessionResp_set_bytes_consumed(s2a_proto_SessionResp *msg, uint32_t value) {
  *UPB_PTR_AT(msg, UPB_SIZE(4, 4), uint32_t) = value;
}
UPB_INLINE void s2a_proto_SessionResp_set_result(s2a_proto_SessionResp *msg, s2a_proto_SessionResult* value) {
  _upb_sethas(msg, 2);
  *UPB_PTR_AT(msg, UPB_SIZE(20, 32), s2a_proto_SessionResult*) = value;
}
UPB_INLINE struct s2a_proto_SessionResult* s2a_proto_SessionResp_mutable_result(s2a_proto_SessionResp *msg, upb_arena *arena) {
  struct s2a_proto_SessionResult* sub = (struct s2a_proto_SessionResult*)s2a_proto_SessionResp_result(msg);
  if (sub == NULL) {
    sub = (struct s2a_proto_SessionResult*)_upb_msg_new(&s2a_proto_SessionResult_msginit, arena);
    if (!sub) return NULL;
    s2a_proto_SessionResp_set_result(msg, sub);
  }
  return sub;
}
UPB_INLINE void s2a_proto_SessionResp_set_status(s2a_proto_SessionResp *msg, s2a_proto_SessionStatus* value) {
  _upb_sethas(msg, 3);
  *UPB_PTR_AT(msg, UPB_SIZE(24, 40), s2a_proto_SessionStatus*) = value;
}
UPB_INLINE struct s2a_proto_SessionStatus* s2a_proto_SessionResp_mutable_status(s2a_proto_SessionResp *msg, upb_arena *arena) {
  struct s2a_proto_SessionStatus* sub = (struct s2a_proto_SessionStatus*)s2a_proto_SessionResp_status(msg);
  if (sub == NULL) {
    sub = (struct s2a_proto_SessionStatus*)_upb_msg_new(&s2a_proto_SessionStatus_msginit, arena);
    if (!sub) return NULL;
    s2a_proto_SessionResp_set_status(msg, sub);
  }
  return sub;
}

#ifdef __cplusplus
}  /* extern "C" */
#endif

#include "upb/port_undef.inc"

#endif  /* PROTO_S2A_PROTO_UPB_H_ */
